Repository googleapis/java-pubsublite, pull requests merged in 2020-06, with the labels that each got.

#90 fix: Modify CommitterImpl to exit early in case of permanent failure
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
Labels: cla: yes

#96 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#98 samples: update lib version
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#100 chore: turn on renovate-bot master issue for java repos
  README.md
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#116 build(java): skip lint on samples directory
  .kokoro/build.sh
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#81 fix: Return an error on publish if the publisher's state is not RUNNING
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java
Labels: cla: yes

#92 Implements batching of flow control requests
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/TokenCounter.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Labels: cla: yes

#120 [feat] Remove custom deduplication logic in favor of beam Deduplicate.
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/DeduplicationFn.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/DeduplicationFnOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransform.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransformTest.java
Labels: cla: yes

#125 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#137 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#132 feat: Import and build new Pub/Sub Lite assignment protos
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentServiceGrpc.java
  pom.xml
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialPartitionAssignmentRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialPartitionAssignmentRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignment.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentAck.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentAckOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscriberProto.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  pubsublite-beam-io/pom.xml
Labels: cla: yes

#134 feat: Modify and test ConnectedAssignerImpl and AssignerImpl
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionAssignmentReceiver.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java
Labels: cla: yes

#135 feat: Implement AssigningSubscriber which uses the PartitionAssignmentService to determine which partitions to connect to.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/PartitionSubscriberFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerFactory.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
Labels: cla: yes

#142 fix: Add missing monitor from startSubscriber.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriber.java
Labels: cla: yes

#143 fix: Fix assorted lint errors.
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Labels: cla: yes

#144 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#149 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#151 fix: Update SingleConnection to not hold the monitor on upcalls
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java
Labels: cla: yes

#153 test: Add VPC-SC Negative Integration Tests
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/it/ITVPCNegativeTest.java
Labels: cla: yes
