Repository googleapis/java-pubsublite, pull requests merged in 2020-07, with the labels that each got.

#155 samples: update readme samples
  .readme-partials.yaml
  README.md
  synth.metadata
Labels: cla: yes

#152 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  google-cloud-pubsublite/pom.xml
  pubsublite-beam-io/pom.xml
Labels: cla: yes, context: full

#162 chore: README version update
  README.md
  synth.metadata
Labels: cla: yes, context: none

#168 feat: Add proto and java generated files for the TopicStatsService
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/AdminServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CursorServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PublisherServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscriberServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicStatsServiceGrpc.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/AttributeValues.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CommitCursorRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeMessageStatsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeMessageStatsRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeMessageStatsResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeMessageStatsResponseOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CreateSubscriptionRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CreateTopicRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/Cursor.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/DeleteSubscriptionRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/DeleteTopicRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/FlowControlRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/GetSubscriptionRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/GetTopicPartitionsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/GetTopicRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialCommitCursorRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialPartitionAssignmentRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialPublishRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialSubscribeRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/InitialSubscribeResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListPartitionCursorsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListPartitionCursorsResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListSubscriptionsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListSubscriptionsResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListTopicSubscriptionsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListTopicSubscriptionsResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListTopicsRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ListTopicsResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/MessagePublishRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/MessagePublishResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/MessageResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignment.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionCursor.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PubSubMessage.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PublishRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PublishResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SeekRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SeekResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SequencedCommitCursorRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SequencedCommitCursorResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SequencedMessage.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/StreamingCommitCursorRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/StreamingCommitCursorResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscribeRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscribeResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/Subscription.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/Topic.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicPartitions.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicStatsProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/UpdateSubscriptionRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/UpdateTopicRequest.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/topic_stats.proto
Labels: cla: yes

#170 docs: Update beam readme to suggest maven sources.
  pubsublite-beam-io/README.md
Labels: cla: yes

#175 chore: mark certain proto fields as required and reformat files
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/admin.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/common.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/cursor.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/publisher.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/topic_stats.proto
  synth.metadata
Labels: cla: yes, context: none
