Repository googleapis/java-pubsublite, pull requests merged in 2020-11, with the labels that each got.

#344 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#349 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#350 Update README.md
  pubsublite-beam-io/README.md
Labels: api: pubsublite, cla: yes

#355 chore: Delete kafka client, it has been moved to https://github.com/googleapis/java-pubsublite-kafka
  pom.xml
  pubsublite-kafka-shim/README.md
  pubsublite-kafka-shim/pom.xml
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/CommitterFactory.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerFactory.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/KafkaExceptionUtils.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/LiteHeaders.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteNode.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PullSubscriberFactory.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/RecordTransforms.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SharedBehavior.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumer.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImpl.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/RecordTransformsTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImplTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/StatusTestHelpers.java
Labels: api: pubsublite, cla: yes

#357 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#359 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#358 samples: update create topic sample and comments
  samples/snippets/src/main/java/pubsublite/CreateSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
  samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
Labels: api: pubsublite, cla: yes

#369 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, cla: yes

#379 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#377 feat: Implement TopicConfigWatcher
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/ApiExceptionMatcher.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImplTest.java
Labels: api: pubsublite, cla: yes

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, cla: yes

#384 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#388 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full, samples
