Repository googleapis/java-pubsublite, pull requests merged in 2020-10, with the labels that each got.

#271 chore: Move FakeApiService to testing folder and add UnitTestExamples
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/FakeApiService.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/UnitTestExamples.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriberTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
Labels: cla: yes

#273 feat: Add pubsublite-kafka-shim directory and disable deployment
  pom.xml
  pubsublite-kafka-shim/pom.xml
Labels: cla: yes

#275 deps: Move common dependencies into parent dependency management section
  google-cloud-pubsublite/pom.xml
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriberTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
  pom.xml
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
Labels: cla: yes

#272 feat: Add nextOffset method to BufferingPullSubscriber
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/PullSubscriber.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriberTest.java
Labels: api: pubsublite, cla: yes

#278 feat: Add SharedBehavior class which handles the PartitionsFor method on consumers and producers
  pubsublite-kafka-shim/pom.xml
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SharedBehavior.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
Labels: cla: yes

#280 feat: Implement PubsubLiteProducer
  pubsublite-kafka-shim/pom.xml
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java
Labels: api: pubsublite, cla: yes

#281 feat: Implement SingleSubscriptionConsumerImpl
  pubsublite-kafka-shim/pom.xml
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImpl.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImplTest.java
Labels: api: pubsublite, cla: yes

#287 feat: Implement PubsubLiteConsumer.
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
Labels: api: pubsublite, cla: yes

#289 fix: Make connections start up asynchronously
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionHelpers.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Labels: api: pubsublite, cla: yes

#300 fix: Change internals to throw StatusException instead of return Status
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/BatchPublisherImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitState.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionObserver.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/Subscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitStateTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Labels: cla: yes

#301 fix: Implement ApiResourceAggregation to deduplicate logic for BackgroundResources.
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ApiBackgroundResource.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ApiResourceAggregation.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java
Labels: cla: yes

#302 fix: Implement TrivialProxyService to remove duplicate ProxyService logic for the trivial case.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/MultiPartitionSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TrivialProxyService.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisher.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Labels: cla: yes

#288 chore: regenerate common templates
  .github/CODEOWNERS
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .github/workflows/samples.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  CONTRIBUTING.md
  LICENSE
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: partial

#313 fix: Fix PubsubLiteUnboundedSource to create n partitions not partitions of n size
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
Labels: cla: yes

#311 chore(pubsublite): update grpc service config
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStubSettings.java
  synth.metadata
Labels: cla: yes, context: full

#315 docs: Update README.md
  pubsublite-beam-io/README.md
Labels: cla: yes

#305 fix: Add generated serialization id to TopicBacklogReaderSettings
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
Labels: api: pubsublite, cla: yes

#317 deps: Increment beam version on pubsublite-io
  pubsublite-beam-io/pom.xml
Labels: cla: yes

#312 chore: Re-generated to pick up changes from synthtool.
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/formatting.yaml
  .kokoro/build.sh
  renovate.json
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, cla: yes

#319 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#320 docs: Add a basic readme for kafka client
  pubsublite-kafka-shim/README.md
Labels: cla: yes

#322 fix: Change Kafka{Producer/Consumer} to fix the number of partitions
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
  pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SharedBehavior.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java
  pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
Labels: api: pubsublite, cla: yes

#326 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#331 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#332 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#337 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#338 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#342 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#343 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
