Repository googleapis/java-pubsublite, pull requests merged in 2020-08, with the labels that each got.

#184 fix: add clirr ignored diffs files
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/pom.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Stubs.java
  proto-google-cloud-pubsublite-v1/clirr-ignored-differences.xml
  proto-google-cloud-pubsublite-v1/pom.xml
  pubsublite-beam-io/clirr-ignored-differences.xml
  pubsublite-beam-io/pom.xml
Labels: cla: yes

#181 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#190 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#182 feat: add api client headers to outbound requests
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Stubs.java
Labels: cla: yes

#194 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#163 feat: Add the ability to use automatic subscriber assignment to the subscriber settings
  google-cloud-pubsublite/pom.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java
Labels: cla: yes

#196 chore: Remove blanket disable of clirr, add gax files to clirr-ignored-differences.xml
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/pom.xml
Labels: cla: yes

#193 chore: add grpc service config json
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/package-info.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStubSettings.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentServiceGrpc.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  synth.metadata
Labels: cla: yes, context: full

#189 samples: update samples for automatic subscriber assignment
  .readme-partials.yaml
  samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
  samples/snippets/src/main/java/pubsublite/SubscriberExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes

#198 Revert "samples: update samples for automatic subscriber assignment"
  .readme-partials.yaml
  samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
  samples/snippets/src/main/java/pubsublite/SubscriberExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes

#199 samples: update samples for automatic subscriber assignment
  .readme-partials.yaml
  samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
  samples/snippets/src/main/java/pubsublite/SubscriberExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes

#202 chore: update readme
  README.md
  synth.metadata
Labels: cla: yes, context: none

#208 samples: lint
  samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/UpdateTopicExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes

#210 fix: change toString to value in TopicStatsClient
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java
Labels: cla: yes

#212 samples: remove extra semicolon
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes

#211 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#218 fix: add test coverage for cloudpubsub folder.
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
Labels: cla: yes

#219 chore: fix synth.metadata file list
  synth.metadata
Labels: cla: yes

#220 fix: Add more coverage
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClientSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Stubs.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientSettingsTest.java
Labels: cla: yes

#221 fix: Add Documentation
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClientSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/CloudRegion.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/CloudZone.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Endpoints.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ErrorCodes.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/LocationPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/LocationPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Message.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/MessageTransformer.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Offset.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Partition.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/PartitionLookupUtils.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectNumber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/PublishMetadata.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SequencedMessage.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Stubs.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionName.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicName.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/FlowControlSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/KeyExtractor.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/MessageTransforms.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/NackHandler.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/Publisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/Subscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CloseableMonitor.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/FakeApiService.java
Labels: api: pubsublite, cla: yes

#225 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#226 feat: Add the TopicBacklogReader
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImpl.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImplTest.java
Labels: api: pubsublite, cla: yes
