Repository googleapis/java-pubsublite, pull requests merged in 2020-09, with the labels that each got.

#232 deps: update shared-dependencies to a version with a working GRPC version.
  pom.xml
Labels: cla: yes

#231 fix: Embed builder in path classes and make components directly accessible
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/LocationPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/LocationPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/PartitionLookupUtils.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectLookupUtils.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicPath.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicPaths.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/BatchPublisherImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/it/ITVPCNegativeTest.java
  pubsublite-beam-io/README.md
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImplTest.java
Labels: cla: yes

#235 docs: Update samples for v0.3.0
  .readme-partials.yaml
  README.md
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/CreateSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
  samples/snippets/src/main/java/pubsublite/DeleteSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/DeleteTopicExample.java
  samples/snippets/src/main/java/pubsublite/GetSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/GetTopicExample.java
  samples/snippets/src/main/java/pubsublite/ListSubscriptionsInProjectExample.java
  samples/snippets/src/main/java/pubsublite/ListSubscriptionsInTopicExample.java
  samples/snippets/src/main/java/pubsublite/ListTopicsExample.java
  samples/snippets/src/main/java/pubsublite/PublishWithBatchSettingsExample.java
  samples/snippets/src/main/java/pubsublite/PublishWithCustomAttributesExample.java
  samples/snippets/src/main/java/pubsublite/PublishWithOrderingKeyExample.java
  samples/snippets/src/main/java/pubsublite/PublisherExample.java
  samples/snippets/src/main/java/pubsublite/SubscriberExample.java
  samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
  samples/snippets/src/main/java/pubsublite/UpdateTopicExample.java
Labels: api: pubsublite, cla: yes

#238 Create a pool of Channels for each target.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ChannelCache.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/ChannelCacheTest.java
Labels: cla: yes

#239 Split retryable codes for streams, and add retry for stream operations.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ErrorCodes.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
Labels: cla: yes

#241 fix: Fix warning due to unchecked cast.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectBuilderHelper.java
Labels: cla: yes

#227 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#244 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#228 feat: Use TopicStats to implement getSplitBacklog
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
Labels: api: pubsublite, cla: yes

#246 fix: Assorted warnings.
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectLookupUtils.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingMetadata.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilderTest.java
Labels: cla: yes

#245 chore: Update DefaultRoutingPolicyTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/DefaultRoutingPolicyTest.java
Labels: cla: yes

#236 [CHANGE ME] Re-generated to pick up changes from googleapis.
  .github/CODEOWNERS
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CommonProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/MessagePublishRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/MessagePublishRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SequencedMessage.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/Topic.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/common.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/cursor.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/publisher.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full, context: partial

#249 chore: Move BufferingPullSubscriber into google-cloud-pubsublite
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/PullSubscriber.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriberTest.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
Labels: api: pubsublite, cla: yes

#252 feat: Implement internal CursorClient
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientImpl.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientSettings.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/CursorClientImplTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/CursorClientSettingsTest.java
Labels: cla: yes

#253 fix: Fix BufferingPullSubscriber to not seek after sending flow control tokens.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriberTest.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
Labels: cla: yes

#254 fix: Move settings for the topic backlog reader to TopicBacklogReaderSettings
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
Labels: cla: yes

#256 fix: Make BufferingPullSubscriber use List instead of ImmutableList
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/PullSubscriber.java
Labels: cla: yes

#265 fix: Make flogger a runtime dependency by default.
  README.md
  google-cloud-pubsublite/pom.xml
  pubsublite-beam-io/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#267 chore: update readme
  README.md
  synth.metadata
Labels: api: pubsublite, cla: yes, context: none

#250 chore: manage repo settings
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, cla: yes
