Repository googleapis/java-pubsublite, pull requests merged in 2021-02, with the labels that each got.

#475 feat: Add CredentialsProvider to Publisher and Subscriber settings
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilderTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
Labels: api: pubsublite, cla: yes

#478 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#479 feat: remove beam I/O from pubsublite github and redirect to beam version instead
  pom.xml
  pubsublite-beam-io/EnableAutoValue.txt
  pubsublite-beam-io/README.md
  pubsublite-beam-io/clirr-ignored-differences.xml
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/AddUuidsTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/CloudPubsubTransforms.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/MessageCoder.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetCheckpointMark.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetFinalizer.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerServerPublisherCache.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherCache.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherOrError.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteIO.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteSink.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SequencedMessageCoder.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SerializableStatusFunction.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SerializableSupplier.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Uuid.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/package-info.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/templates/FakePubsubIO.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/templates/PubsubLiteConverters.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/templates/PubsubLiteToPubsub.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/templates/PubsubToPubsubLite.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/templates/package-info.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/AddUuidsTransformTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/FakeSerializable.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/MessageCoderTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/OffsetCheckpointMarkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SequencedMessageCoderTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImplTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransformTest.java
Labels: api: pubsublite, cla: yes

#438 chore: update gapic-generator-java to 0.0.16
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/CursorServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PublisherServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/SubscriberServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcAdminServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcCursorServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPartitionAssignmentServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPublisherServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcSubscriberServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcTopicStatsServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStubSettings.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/AdminServiceClientTest.java
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#486 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: partial

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#482 feat: Change message id on PubsubMessages to be an encoded MessageMetadata and rename PublishMetadata to MessageMetadata
  .readme-partials.yaml
  README.md
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/MessageMetadata.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/MessageTransforms.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionPublisherFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherBuilder.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisher.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherBuilder.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/MessageMetadataTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/MessageTransformsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
  samples/snippets/src/main/java/pubsublite/PublishWithBatchSettingsExample.java
  samples/snippets/src/main/java/pubsublite/PublishWithCustomAttributesExample.java
  samples/snippets/src/main/java/pubsublite/PublishWithOrderingKeyExample.java
  samples/snippets/src/main/java/pubsublite/PublisherExample.java
  samples/snippets/src/main/java/pubsublite/SubscriberExample.java
Labels: api: pubsublite, cla: yes

#490 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  LICENSE
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#493 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#499 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#498 docs: generate sample code in the Java microgenerator
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/CursorServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PublisherServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/SubscriberServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/package-info.java
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full, samples

#502 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#501 chore: update gapic-generator-java to 0.0.20
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcAdminServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcCursorServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPartitionAssignmentServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPublisherServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcSubscriberServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcTopicStatsServiceStub.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockAdminServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockCursorServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPartitionAssignmentServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPublisherServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockSubscriberServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockTopicStatsServiceImpl.java
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#503 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#506 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#507 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#509 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/gapic_metadata.json
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#513 feat: Re-fork the beam repo from upstream
  pom.xml
  pubsublite-beam-io/README.md
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/AddUuidsTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/CloudPubsubChecks.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/DlqProvider.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/InitialOffsetReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/InitialOffsetReaderImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/LimitingTopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteProgress.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTracker.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerServerPublisherCache.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdf.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherCache.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherOrError.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteIO.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteSink.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SerializableSubscriberFactory.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SerializableSupplier.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartition.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionCoder.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionLoader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessor.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorFactory.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Uuid.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidCoder.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/package-info.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/AddUuidsTransformTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/FakeSerializable.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTrackerTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdfTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionLoaderTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImplTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImplTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransformTest.java
Labels: api: pubsublite, cla: yes

#514 fix: Fix bundle finalizers
  pubsublite-beam-io/pom.xml
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/LimitingTopicBacklogReader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTracker.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdf.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherCache.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteSink.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionLoader.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImpl.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/AddUuidsTransformTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTrackerTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdfTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImplTest.java
  pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/UuidDeduplicationTransformTest.java
Labels: api: pubsublite, cla: yes, kokoro:force-run

#496 fix: Rebatch messages when restarting a publish stream
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java
Labels: api: pubsublite, cla: yes

#522 build: fix version replacement in pubsublite-beam-io
  pubsublite-beam-io/pom.xml
Labels: api: pubsublite, cla: yes

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#529 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#532 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes
