Repository googleapis/java-pubsublite, pull requests merged in 2021-04, with the labels that each got.

#573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#574 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#571 fix: Allow setting framework tags on cloud pubsub shim.
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
Labels: api: pubsublite, cla: yes

#579 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#586 docs: improve PubsubLiteIO readme
  pubsublite-beam-io/README.md
Labels: api: pubsublite, cla: yes

#590 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#595 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#597 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes, kokoro:force-run

#598 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#600 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#603 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#615 feat: ComputeTimeCursor RPC for Pub/Sub Lite
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/gapic_metadata.json
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcTopicStatsServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStubSettings.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockTopicStatsServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClientTest.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicStatsServiceGrpc.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/AdminProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CommonProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeTimeCursorRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeTimeCursorRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeTimeCursorResponse.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/ComputeTimeCursorResponseOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscriberProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TimeTarget.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TimeTargetOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicStatsProto.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/admin.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/common.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/topic_stats.proto
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#616 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#618 feat: Compute cursors for publish and event timestamps
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java
Labels: api: pubsublite, cla: yes

#620 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#623 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes
