Repository googleapis/java-pubsublite, pull requests merged in 2021-03, with the labels that each got.

#520 chore: use single white space for comments
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java
  synth.metadata
Labels: api: pubsublite, cla: yes, context: none

#537 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#538 chore: remove Constants.java from the list of generated files in synth.metadata
  synth.metadata
Labels: api: pubsublite, cla: yes

#539 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#541 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#540 chore(release): update Java microgenerator to 1.0.1
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/CursorServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/CursorServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PublisherServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/PublisherServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/SubscriberServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/SubscriberServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/package-info.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/AdminServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/CursorServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcAdminServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcAdminServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcCursorServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcCursorServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPartitionAssignmentServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPartitionAssignmentServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPublisherServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcPublisherServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcSubscriberServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcSubscriberServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcTopicStatsServiceCallableFactory.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/GrpcTopicStatsServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PartitionAssignmentServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/PublisherServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/SubscriberServiceStubSettings.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStub.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/stub/TopicStatsServiceStubSettings.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/AdminServiceClientTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/CursorServiceClientTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockAdminService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockAdminServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockCursorService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockCursorServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPartitionAssignmentService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPartitionAssignmentServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPublisherService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPublisherServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockSubscriberService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockSubscriberServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockTopicStatsService.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockTopicStatsServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/PartitionAssignmentServiceClientTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/PublisherServiceClientTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/SubscriberServiceClientTest.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClientTest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/LocationName.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscriptionName.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicName.java
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#543 feat: add skip_backlog field to allow subscriptions to be created at HEAD
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/TopicStatsServiceClient.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/AdminServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CursorServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PartitionAssignmentServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PublisherServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/SubscriberServiceGrpc.java
  grpc-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/TopicStatsServiceGrpc.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/AdminProto.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CreateSubscriptionRequest.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/CreateSubscriptionRequestOrBuilder.java
  proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/Topic.java
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/admin.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/common.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/cursor.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/publisher.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/subscriber.proto
  proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/topic_stats.proto
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#547 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#549 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/AdminServiceClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/v1/CursorServiceClient.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockAdminServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockCursorServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPartitionAssignmentServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockPublisherServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockSubscriberServiceImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/v1/MockTopicStatsServiceImpl.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#552 fix: Two QOL issues with PubsubLiteIO
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Uuid.java
Labels: api: pubsublite, cla: yes

#553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#554 docs: Add documentation on drain support requirements
  pubsublite-beam-io/README.md
Labels: api: pubsublite, cla: yes

#555 docs: Update Readme.md to reflect not-yet-released state of beam 2.29.0
  pubsublite-beam-io/README.md
Labels: api: pubsublite, cla: yes

#559 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#545 feat: Adding ability to create a subscription at HEAD
  google-cloud-pubsublite/clirr-ignored-differences.xml
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
  google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java
Labels: api: pubsublite, cla: yes

#562 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full, samples

#563 fix: Set batching settings on SinglePartitionPublisher
  pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java
Labels: api: pubsublite, cla: yes

#564 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full
