Repository googleapis/java-pubsublite, pull requests merged in 2021-08, with the labels that each got.

#791 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, automerge, cla: yes

#793 chore: replace dependencyDashboard with masterIssue in renovate.json
  renovate.json
  synth.metadata
Labels: api: pubsublite, cla: yes, context: none

#792 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: pubsublite, automerge, cla: yes

#800 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#799 chore: remove internal packages from javadoc
  pom.xml
Labels: cla: yes, api: pubsublite

#804 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#812 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#771 samples: Add seek subscription sample
  google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java
  samples/snippets/src/main/java/pubsublite/SeekSubscriptionExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: cla: yes, api: pubsublite, samples

#813 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#819 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#825 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#831 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: automerge, cla: yes, api: pubsublite, context: full

#833 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#835 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#846 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#845 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: pubsublite
