Repository googleapis/java-pubsublite, pull requests merged in 2024-04, with the labels that each got.

#1628 ci: remove Kokoro sample from required checks
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, samples, size: xs

#1632 chore: include recommended_package in repo-metadata.json
  .repo-metadata.json
Labels: api: pubsublite, size: xs

#1638 chore: Allow Cloud Java to merge in Java code changes
  .github/CODEOWNERS
  owlbot.py
Labels: automerge, kokoro:force-run, api: pubsublite, size: xs
